---
title: 'Peer Code Review: Checklist and Reflection'
author: "Ellen Bledsoe"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# Checklist and Reflection (20 points)

In this .Rmd file, you will find (a) the checklist to complete for the peer code review and (b) a short reflection about the experience.

Once both are completed, knit this document and submit to the Peer Code Review Assignment on D2L.

### GitHub Repo

Whose repo did you review? Include the link to the repo here.

Name: Cameron Crowder

Link to Repo: <https://github.com/LyraRahner/Crowder_FinalProject.git>

## Checklist

Complete the checklist, where appropriate, based on your review. If you are in visual mode, you can actually "check" the boxes by clicking on them. If you are working in source mode, you will put an `x` inside the square brackets next to each item.

Since you are reviewing a "Work in Progress" project, not all boxed might be checked; that's ok! That will not impact anyone's grade :)

### Repository Setup

-   [x] I accessed and cloned the repository.
-   [x] A README is present.
    -   [ ] README explains project purpose.
    -   [x] README includes reproduction instructions.

### Code Clarity & Readability

-   [x] Variable names are descriptive.
-   [x] Code is logically structured.
-   [x] Helpful comments are included.
-   [x] Code is generally readable.

**Notes / Comments:**\
\>The only thing I would mention is that some of the data frame names are not very helpful but the variables are named well. The comments are helpful although some of their code I didn't understand but that's more of a me problem.

### Functionality

-   [x] Code runs without errors.
-   [x] Outputs match expectations or are explained.
-   [x] All file paths are relative.

**Notes / Comments:**\
\> I checked that the code runs without errors because overall it does. The only issue was that the file path to read in the data and one of the plots didn't work. I have a feeling they just moved their markdown file into their working directory rather than their scripts folder and that messed the file path up.

### Code Organization

-   [ ] Files and folders are logically structured.
-   [x] Workflow is understandable and modular.
-   [x] Reproducibility is supported.

**Notes / Comments:**\
\>The folders and files are a bit confusing. In their scripts folder they have a markdown file that just called "Script" and it has basically no code in it. Then in their working directory they have another markdown file thats also called "script" and this has their final project in it. They should probably name the scrip with the final project in it something like "final_project" move it to the scrips folder and delete the extra script. Other than that everything makes sense. Most of the file paths work and are reproducible. Workflow is logical and there are comments.

### Documentation

-   [ ] README is complete and clear.
-   [x] RMarkdown file or R scripts include informative text and/or comments.
-   [x] Data or package requirements are documented.

**Notes / Comments:**\
\> The readme file is not complete I imagine that they just haven't gotten to it yet. What would be helpful for me in the read me is if they gave me a brief description of the purpose of the code.

### Suggestions for Improvement

List **three** actionable suggestions:

1.  One easy thing to fix would be the file paths. They could either put the markdown script in the scripts folder (this is what I would do) or change the file path so that the data set that everything is build off of reads in. For the plots the file path on one of them works as is but the other would only work if the markdown file was in the scripts folder. I also would change the name of their final project script into something other than "Script"

2.  Another suggestion I made was to save their data set after it was cleaned up into a data_clean folder (which they didn't have so i made one)

3.  I also made some suggestions on their plots that I think improve readability.

## Reflection

Write 7-10 sentences summarizing your review experience:

-   What was done well?
-   What was challenging about this assignment?
-   What did you learn for your own projects?
-   How did you approach constructive feedback?

**Reflection**:

I think this code was overall done well. The comments were clear and helped me follow along, the code seemed logical and streamline. It was all reproducible and I was to run everything without errors once I fixed the first file path. This assignment was changeling because I do not feel proficient enough in R to give someone else advice. There were a couple parts of this code that I feel like there should be a faster way to do it but I just did not know how to figure it out. From reviewing this code I learned that comments are really helpful if you are unfamiliar with the code and data. I think I'll add some more comments to my final code. I also realized how confusing other peoples directory set up can be and I'm going to make sure mine is organized and well labeled. I tried to add feedback that would be genualy helpful and streamline their code. I mostly explained what I meant by copy/pasting their code adding my suggestions then commenting it out.

## Submission

Upload the knitted `.pdf` file to the "Peer Code Review" Assignment on D2L.
